### ISSUE TITLE
Wrapper not catching 400 bad request errors from API on clanChest.

### ISSUE THREAD

**Issue by BlackHoleFox** [TheLearneer/croyale#5]
(Issue title pretty self explanatory)

Expected Result: Upon getting clanChest stats of invalid clan tag, an Improper request error from wrapper.

Actual Result: 400 bad request error from the API itself.

**Comment by BlackHoleFox** [comment]
Figured since it will tell you if a tag is invalid, it should catch this too?

**Comment by bsantosh909** [comment]
Ok, so if you are talking of conditions of tags with proper characters but the tag is not a proper tag.
i.e. https://gearz.has-a-bad.website/GYjPhZPbp.png
If you have a look at this link. I have used a player tag to fetch clan profile it returns 404, because the tag has valid tag characters but still is not a valid clan tag.

So closing this for now.
